### ISSUE TITLE
Upgrade actions with canonical plugin for LXD

### ISSUE THREAD

**Issue by deusebio** [canonical/spark-rock#2]
In the CI/CD pipeline, we are currently using the following plug

```
- name: Setup LXD
  uses: whywaita/setup-lxd@v1
```

which is not mantained and supported. The goal is to use `canonical/setup-lxd@main` instead. However this increases the time spent on CI/CD pipeline, as the plugin tries to update lxd.

There is an active discussion [here](https://github.com/canonical/mongodb-rock/pull/2). Depending on the outcome there, we should align the code in this repo

**Comment by taurus-forever** [comment]
We can switch to `canonical/setup-lxd@main`now, PR prepared.
