### ISSUE TITLE
ROCK will need to use NB_PREFIX env var for Kubeflow integrations

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/spark-rock#66]
Creating an issue after our findings with @deusebio, for integrating the PySpark ROCK with Kubeflow.

In Kubeflow we deploy jupyter notebooks as a CustomResource, handled by a Charmed Notebooks K8s Controller, which will end up creating STS/Pod for the Notebook requested by the CR.

In Kubeflow all notebooks will be exposed under a different prefix and the servers will need to be aware of this prefix. For this the Charmed Notebooks K8s Controller will end up adding a `NB_PREFIX` env var, which should be used when launching jupyterlab. Here's an example of how this is used from upstream KF Notebook images:
https://github.com/kubeflow/kubeflow/blob/master/components/example-notebook-servers/jupyter/s6/services.d/jupyterlab/run#L19

Currently this ROCK doesn't take this into account, so the final jupyterlab UI is not accessible to users in Kubeflow, since the server is exposed in a different prefix from the one it's configured to listen to (`/`)

**Comment by deusebio** [comment]
We have addressed this issue in a recent PR that I have now referenced to the issue
